# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: false
cache:
  - packages: true

warnings_are_errors: true
r_check_args: "--as-cran"

apt_packages:
  - libglpk-dev

matrix:
  include:
  - r: release
    r_packages:
    - devtools
    - pkgdown
    - covr
    after_success:
    - R CMD INSTALL $PKG_TARBALL
    - Rscript -e 'devtools::check()'
    - Rscript -e 'covr::coveralls()'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: devel

notifications:
  email:
    on_success: always
    on_failure: always
